Feature: B-41888 Enhance LCLA integration with High Priority Data -following attributes
   APPLICATION_INPUT_PROCESSING_METHOD_TYPE
   INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT
   INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT
   INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE
   INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE

  @sitint 
  Scenario Outline: Send request using the PMLAPP Client and then validate the data in the DB
    Given a request for sls webservice for id <scenarioid>
    Then setup the Payload with unique values for <SourceSystem>
    Then modify <AttributeName> to create a payload with <AttributeValue>
    Then modify <AttributeName2> to create a payload with <AttributeValue2>
    Then modify <AttributeName3> to create a payload with <AttributeValue3>
    Then modify <AttributeName4> to create a payload with <AttributeValue4>
    Then modify <AttributeName5> to create a payload with <AttributeValue5>
    When the request is sent to the PMLAPP Client
    Then validate that the DB received the payload correctly with EventProcessStatus as <EVAL_PROCSS_STATS>
    And validate that information has been stored correctly in the DB

    Examples: 
      #keys = "" send null in the tag, "null" deletes tag from XML
      | scenarioid | SourceSystem | AttributeName                              | AttributeValue             | AttributeName2                                | AttributeValue2                                        | AttributeName3                                        | AttributeValue3    | AttributeName4                                            | AttributeValue4    | AttributeName5                                        | AttributeValue5        | EVAL_PROCSS_STATS |
      #tc = APPLICATION_INPUT_PROCESSING_METHOD_TYPE
      | "5"        | "LCLA"       | "APPLICATION_INPUT_PROCESSING_METHOD_TYPE" | "UserInterface"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "CashToCloseTotal"                                     | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "10.01"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "ToBorrower"           | "Processed"       |
      | "6"        | "LCLA"       | "APPLICATION_INPUT_PROCESSING_METHOD_TYPE" | ""                         | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "ClosingCostsFinanced"                                 | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "10.01"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "ToBorrower"           | "Processed"       |
      | "7"        | "LCLA"       | "APPLICATION_INPUT_PROCESSING_METHOD_TYPE" | "null"                     | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "Deposit"                                              | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "10.01"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "FromBorrower"         | "Processed"       |
      | "8"        | "LCLA"       | "APPLICATION_INPUT_PROCESSING_METHOD_TYPE" | "UserInterfaceS1234567890" | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "CashToCloseTotal"                                     | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "10.01"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "ToBorrower"           | "Persist_Error"   |
      | "9"        | "LCLA"       | "APPLICATION_INPUT_PROCESSING_METHOD_TYPE" | "UserInterfaceS"           | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "CashToCloseTotal"                                     | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "10.01"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "ToBorrower"           | "Processed"       |
      | "10"       | "LCLA"       | "APPLICATION_INPUT_PROCESSING_METHOD_TYPE" | ""                         | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "ClosingCostsFinanced"                                 | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "10.01"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "ToBorrower"           | "Processed"       |
      #tc = INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE
      | "11"       | "LCLA"       | "APPLICATION_INPUT_PROCESSING_METHOD_TYPE" | "UserInterface"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "CashToCloseTotal"                                     | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "10.01"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "ToBorrower"           | "Processed"       |
      | "12"       | "LCLA"       | "APPLICATION_INPUT_PROCESSING_METHOD_TYPE" | "UserInterface"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | ""                                                     | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "10.01"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "ToBorrower"           | "Processed"       |
      | "13"       | "LCLA"       | "APPLICATION_INPUT_PROCESSING_METHOD_TYPE" | "UserInterface"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "null"                                                 | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "10.01"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "FromBorrower"         | "Processed"       |
      | "14"       | "LCLA"       | "APPLICATION_INPUT_PROCESSING_METHOD_TYPE" | "UserInterface"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "CashToCloseTotalCashToCloseTotalCashToCloseTotalCash" | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "10.01"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "ToBorrower"           | "Persist_Error"   |
      | "15"       | "LCLA"       | "APPLICATION_INPUT_PROCESSING_METHOD_TYPE" | "UserInterface"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "CashToCloseTotal12345"                                | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "10.01"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "ToBorrower"           | "Processed"       |
      | "16"       | "LCLA"       | "APPLICATION_INPUT_PROCESSING_METHOD_TYPE" | "UserInterface"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | ""                                                     | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "10.01"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "ToBorrower"           | "Processed"       |
      #tc = INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT
      | "17"       | "LCLA"       | "APPLICATION_INPUT_PROCESSING_METHOD_TYPE" | "UserInterface"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "CashToCloseTotal"                                     | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "1000.01"          | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "ToBorrower"           | "Processed"       |
      | "18"       | "LCLA"       | "APPLICATION_INPUT_PROCESSING_METHOD_TYPE" | "UserInterface"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "ClosingCostsFinanced"                                 | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | ""                 | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "ToBorrower"           | "Processed"       |
      | "19"       | "LCLA"       | "APPLICATION_INPUT_PROCESSING_METHOD_TYPE" | "UserInterface"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "Deposit"                                              | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "null"             | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "FromBorrower"         | "Processed"       |
      | "20"       | "LCLA"       | "APPLICATION_INPUT_PROCESSING_METHOD_TYPE" | "UserInterface"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "Down Payment"                                         | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "0"                | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "FromBorrower"         | "Processed"       |
      | "21"       | "LCLA"       | "APPLICATION_INPUT_PROCESSING_METHOD_TYPE" | "UserInterface"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "CashToCloseTotal"                                     | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "0"                | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "ToBorrower"           | "Processed"       |
      | "22"       | "LCLA"       | "APPLICATION_INPUT_PROCESSING_METHOD_TYPE" | "UserInterface"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "CashToCloseTotal"                                     | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "-100"             | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "ToBorrower"           | "Processed"       |
      | "23"       | "LCLA"       | "APPLICATION_INPUT_PROCESSING_METHOD_TYPE" | "UserInterface"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "Deposit"                                              | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "-100"             | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "10.0245"          | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "ToBorrower"           | "Persist_Error"   |
      | "24"       | "LCLA"       | "APPLICATION_INPUT_PROCESSING_METHOD_TYPE" | "UserInterface"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "Down Payment"                                         | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "1234567890123.12" | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "FromBorrower"         | "Processed"       |
      #tc = INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT
      | "25"       | "LCLA"       | "APPLICATION_INPUT_PROCESSING_METHOD_TYPE" | "UserInterface"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "CashToCloseTotal"                                     | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "1000.01"          | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "FromBorrower"         | "Processed"       |
      | "26"       | "LCLA"       | "APPLICATION_INPUT_PROCESSING_METHOD_TYPE" | "UserInterface"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "ClosingCostsFinanced"                                 | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | ""                 | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "FromBorrower"         | "Processed"       |
      | "27"       | "LCLA"       | "APPLICATION_INPUT_PROCESSING_METHOD_TYPE" | "UserInterface"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "Deposit"                                              | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "null"             | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "ToBorrower"           | "Processed"       |
      | "28"       | "LCLA"       | "APPLICATION_INPUT_PROCESSING_METHOD_TYPE" | "UserInterface"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "Down Payment"                                         | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "0"                | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "FromBorrower"         | "Processed"       |
      | "29"       | "LCLA"       | "APPLICATION_INPUT_PROCESSING_METHOD_TYPE" | "UserInterface"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "CashToCloseTotal"                                     | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "0"                | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "FromBorrower"         | "Processed"       |
      | "30"       | "LCLA"       | "APPLICATION_INPUT_PROCESSING_METHOD_TYPE" | "UserInterface"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "Deposit"                                              | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "-100"             | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "ToBorrower"           | "Processed"       |
      | "31"       | "LCLA"       | "APPLICATION_INPUT_PROCESSING_METHOD_TYPE" | "UserInterface"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "Down Payment"                                         | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "100.123"          | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "FromBorrower"         | "Persist_Error"   |
      | "32"       | "LCLA"       | "APPLICATION_INPUT_PROCESSING_METHOD_TYPE" | "UserInterface"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "CashToCloseTotal"                                     | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "1234567890123.12" | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "FromBorrower"         | "Processed"       |
      #tc = INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE
      | "33"       | "LCLA"       | "APPLICATION_INPUT_PROCESSING_METHOD_TYPE" | "UserInterface"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "CashToCloseTotal"                                     | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "12.01"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "12.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "FromBorrower"         | "Processed"       |
      | "34"       | "LCLA"       | "APPLICATION_INPUT_PROCESSING_METHOD_TYPE" | "UserInterface"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "ClosingCostsFinanced"                                 | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "12.01"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "12.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | ""                     | "Processed"       |
      | "35"       | "LCLA"       | "APPLICATION_INPUT_PROCESSING_METHOD_TYPE" | "UserInterface"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "ClosingCostsFinanced"                                 | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "12.01"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "12.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "null"                 | "Processed"       |
      | "36"       | "LCLA"       | "APPLICATION_INPUT_PROCESSING_METHOD_TYPE" | "UserInterface"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "CashToCloseTotal"                                     | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "12.01"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "12.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "FromBorrowerFromBorr" | "Persist_Error"   |
      | "37"       | "LCLA"       | "APPLICATION_INPUT_PROCESSING_METHOD_TYPE" | "UserInterface"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "CashToCloseTotal"                                     | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "12.01"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "12.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "FromBoRROwerS"        | "Processed"       |
      | "38"       | "LCLA"       | "APPLICATION_INPUT_PROCESSING_METHOD_TYPE" | "UserInterface"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "ClosingCostsFinanced"                                 | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "12.01"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "12.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | ""                     | "Processed"       |
