Feature: B-49523 Enhance LCLA integration with High Priority Data -following attributes
   ApplicationInputProcessingMethodType
   INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT
   INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT
   INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE
   INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE

  @sitint 
  Scenario Outline: Send request using the PMLAPP Client and then validate the data in the DB
    Given a request for sls webservice for id <scenarioid>
    Then setup the Payload with unique values for <SourceSystem>
    Then modify <AttributeName> to create a payload with <AttributeValue>
    Then modify <AttributeName2> to create a payload with <AttributeValue2>
    Then modify <AttributeName3> to create a payload with <AttributeValue3>
    Then modify <AttributeName4> to create a payload with <AttributeValue4>
    When the request is sent to the PMLAPP Client
    Then validate that the DB received the payload correctly with EventProcessStatus as <EVAL_PROCSS_STATS>
    And validate that information has been stored correctly in the DB

    Examples: 
      #keys = "" send null in the tag, "null" deletes tag from XML
      | scenarioid | SourceSystem | AttributeName                                 | AttributeValue                                         | AttributeName2                                        | AttributeValue2    | AttributeName3                                            | AttributeValue3    | AttributeName4                                        | AttributeValue4        | EVAL_PROCSS_STATS |
      | "130"      | "LCLA"       | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "CashToCloseTotal"                                     | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "10.01"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "ToBorrower"           | "Processed"       |
      | "131"      | "LCLA"       | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | ""                                                     | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "10.01"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "ToBorrower"           | "Processed"       |
      | "132"      | "LCLA"       | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "null"                                                 | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "10.01"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "FromBorrower"         | "Processed"       |
      | "133"      | "LCLA"       | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "CashToCloseTotalCashToCloseTotalCashToCloseTotalCash" | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "10.01"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "ToBorrower"           | "Persist_Error"   |
      | "134"      | "LCLA"       | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "CashToCloseTotal12345"                                | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "10.01"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "ToBorrower"           | "Processed"       |
      | "135"      | "LCLA"       | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | ""                                                     | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "10.01"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "ToBorrower"           | "Processed"       |
      #tc = INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT
      | "136"      | "LCLA"       | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "null"                                                 | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "1000.01"          | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "ToBorrower"           | "Processed"       |
      | "137"      | "LCLA"       | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "null"                                                 | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | ""                 | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "ToBorrower"           | "Processed"       |
      | "138"      | "LCLA"       | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "null"                                                 | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "null"             | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "FromBorrower"         | "Processed"       |
      | "139"      | "LCLA"       | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "null"                                                 | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "0"                | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "FromBorrower"         | "Processed"       |
      | "140"      | "LCLA"       | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "null"                                                 | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "0"                | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "ToBorrower"           | "Processed"       |
      | "141"      | "LCLA"       | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "CashToCloseTotal"                                     | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "-100"             | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "ToBorrower"           | "Processed"       |
      | "142"      | "LCLA"       | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "null"                                                 | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "-100"             | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "10.0245"          | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "ToBorrower"           | "Persist_Error"   |
      | "143"      | "LCLA"       | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "null"                                                 | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "1234567890123.12" | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "FromBorrower"         | "Processed"       |
      #tc = INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT
      | "144"      | "LCLA"       | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "null"                                                 | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "1000.01"          | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "FromBorrower"         | "Processed"       |
      | "145"      | "LCLA"       | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "null"                                                 | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | ""                 | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "FromBorrower"         | "Processed"       |
      | "146"      | "LCLA"       | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "null"                                                 | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "null"             | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "ToBorrower"           | "Processed"       |
      | "147"      | "LCLA"       | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "null"                                                 | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "0"                | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "FromBorrower"         | "Processed"       |
      | "148"      | "LCLA"       | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "null"                                                 | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "0"                | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "FromBorrower"         | "Processed"       |
      | "149"      | "LCLA"       | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "null"                                                 | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "-100"             | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "ToBorrower"           | "Processed"       |
      | "150"      | "LCLA"       | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "null"                                                 | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "100.123"          | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "FromBorrower"         | "Persist_Error"   |
      | "151"      | "LCLA"       | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "null"                                                 | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "10.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "1234567890123.12" | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "FromBorrower"         | "Processed"       |
      #tc = INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE
      | "152"      | "LCLA"       | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "null"                                                 | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "12.01"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "12.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "FromBorrower"         | "Processed"       |
      | "153"      | "LCLA"       | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "null"                                                 | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "12.01"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "12.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | ""                     | "Processed"       |
      | "154"      | "LCLA"       | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "null"                                                 | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "12.01"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "12.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | ""                     | "Processed"       |
      | "155"      | "LCLA"       | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "null"                                                 | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "12.01"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "12.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "FromBorrowerFromBorr" | "Persist_Error"   |
      | "156"      | "LCLA"       | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "null"                                                 | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "12.01"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "12.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | "FromBoRROwerS"        | "Processed"       |
      | "157"      | "LCLA"       | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_TYPE" | "null"                                                 | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_FINAL_AMOUNT" | "12.01"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_ESTIMATED_AMOUNT" | "12.02"            | "INTEGRATED_DISCLOSURE_CASHTOCLOSE_ITEM_PAYMENT_TYPE" | ""                     | "Processed"       |
